### PR TITLE
Pre-flight DecodePatch validation: Issue #177

### PR DESCRIPTION
**Pull request by radwaretaltr**
Pre-flight Patch validation in DecodePatch

### CODE REVIEW

**Comment by radwaretaltr** [comment]
Hi @evanphx, 

Can you please assist and take a look at the build failure we are getting. 
Not sure it's related to our changes.

**Comment by evanphx** [comment]
Wow, that's odd.

**Comment by evanphx** [comment]
@radwaretaltr Could you rebase and try again? The go version was bumped to 1.18...

**Comment by radwaretaltr** [comment]
> @radwaretaltr Could you rebase and try again? The go version was bumped to 1.18...

Done.

**Comment by sambercovici** [comment]
Hi @evanphx 
Can you please provide an estimate when you can review this PR/merge?

Thanks, Sam.

**Pull request merged**
