### PR TITLE
Introduce ApplyWithOptions

### LINKED ISSUE #117: Introduce ApplyWithOptions
Implement method `func (p Patch) ApplyWithOptions(doc []byte, options *ApplyOptions) ([]byte, error)` which implements the functionality of `func (p Patch) Apply`, but takes its options from parameter `options` instead of global package-level variables.
`ApplyOptions` is a struct type which includes the following fields:
- `SupportNegativeIndices bool`
- `AccumulatedCopySizeLimit int64`
- `AllowMissingPathOnRemove bool`

Modify `Apply` to call `ApplyWithOptions` and pass the values of package variables `SupportNegativeIndices` and `AccumulatedCopySizeLimit` as default options as well as `false` for option `AllowMissingPathOnRemove`.

### PR DESCRIPTION
**Pull request by vassilvk**
* Implement ApplyWithOptions
* Implement ApplyWithOptions unit tests
* Fix compareJSON to allow comparison of array containers
* Fix previously incorrect "copy" operation tests

Closes #117.

### CODE REVIEW

**Comment by vassilvk** [comment]
Hi @evanphx,

Any feedback?

**Comment by evanphx** [comment]
Hi! Sorry for the delay. I think my main feedback is that we should pass the opts struct down into the methods that have these options, rather than reading it at the top as arguments. The reason here is I can see the next person come along and want to add another option and they'll end up adding another argument unless they can just use the opts struct directly.

Does that make sense?

**Comment by vassilvk** [comment]
Hi - thanks for the feedback.
Yes, it does make sense and I did flip back and forth on that one quite a bit (my first implementation passed down the options).

The main reason I chose to pass explicit parameters was that technically this is cleaner as each private method gets to maintain its independence from the bigger picture (Apply).

That said, I know I’m that “next person” 🙂 - I need yer another option for more “forgiving” add operations.

I will switch to passing the options struct to the private methods.

**Comment by vassilvk** [comment]
@evanphx - I switched to passing options to private methods.
I also updated README to include the new  `ApplyWithOptions` method and new `AllowMissingPathOnRemove` option.
Please review.

**Comment by evanphx** [comment]
Thanks a bunch @vassilvk!

**Comment by AkihiroSuda** [comment]
Would it be possible to create a new release with this? :pray:

**Comment by evanphx** [comment]
@AkihiroSuda This went out in v5.2.0. Sorry for the delay!

**Comment by AkihiroSuda** [comment]
Thanks!

**Pull request merged**
